services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: apps
      POSTGRES_PASSWORD: appspwd
      POSTGRES_DB: ticketdemo
    ports:
      - "5434:5432"
    volumes:
    - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  tempo:
    image: grafana/tempo:2.7.1
    command: ["-config.file=/etc/tempo.yml"]
    volumes:
      - ./tempo.yml:/etc/tempo.yml
    ports:
      - "3200:3200"
      - "4317:4317"
      - "4318:4318"

  grafana:
    image: grafana/grafana:11.6.0
    ports:
      - "3000:3000"
    depends_on:
      - tempo
  
  prometheus:
    image: prom/prometheus:v3.4.2
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  loki:
    image: grafana/loki:3.5.3
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:3.5.3
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - loki

  orderapi:
    build:
      context: .
      dockerfile: OrderApi/Dockerfile
    ports:
      - "8080:8080"
    environment:
      RabbitMq__Host: rabbitmq
      ASPNETCORE_URLS: http://+:8080
    depends_on:
      - rabbitmq
      - tempo

  orderworker:
    build:
      context: .
      dockerfile: OrderWorker/Dockerfile
    environment:
      RabbitMq__Host: rabbitmq
      ConnectionStrings__TicketDb: Host=postgres;Port=5432;Database=ticketdemo;Username=apps;Password=appspwd
    depends_on:
      - rabbitmq
      - postgres